[workspace]
members  = ["common", "pion"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.lints.rust]
unused_qualifications = { level = "warn", priority = 100 }

[workspace.lints.rustdoc]
all = { level = "warn", priority = 0 }

[workspace.lints.clippy]
all      = { level = "warn", priority = 0 }
nursery  = { level = "warn", priority = 0 }
pedantic = { level = "warn", priority = 0 }

[workspace.dependencies]
bumpalo = { version = "3.13.0", features = ["allocator_api"] }
ecow    = { version = "0.2.0" }
ustr    = { version = "1.0.0" }

[profile.dev]
opt-level = 0

debug            = 0
debug-assertions = true
overflow-checks  = true
panic            = "abort"
strip            = "debuginfo"

codegen-units = 256
incremental   = true

lto = false

[profile.release]
opt-level = 3

debug            = 0
debug-assertions = false
overflow-checks  = false
panic            = "abort"
strip            = "debuginfo"

codegen-units = 16
incremental   = false

lto = "thin"
