[package]
name = "pion"

edition = "2021"
version = "0.1.0"

[lints.rust]
unused_qualifications = { level = "warn", priority = 100 }

[lints.rustdoc]
all = { level = "warn", priority = 0 }

[lints.clippy]
all      = { level = "warn", priority = 0 }
nursery  = { level = "warn", priority = 0 }
pedantic = { level = "warn", priority = 0 }

match_bool               = { level = "allow", priority = 100 }
missing_errors_doc       = { level = "allow", priority = 100 }
missing_panics_doc       = { level = "allow", priority = 100 }
module_name_repetitions  = { level = "allow", priority = 100 }
must_use_candidate       = { level = "allow", priority = 100 }
option_if_let_else       = { level = "allow", priority = 100 }
return_self_not_must_use = { level = "allow", priority = 100 }
too_many_lines           = { level = "allow", priority = 100 }

[dependencies]
bumpalo            = { version = "3.13.0", features = ["allocator_api"] }
camino             = { version = "1.1.6" }
clap               = { version = "4.5.1", features = ["derive"] }
codespan-reporting = { version = "0.11.1" }
ecow               = { version = "0.2.0" }
either             = { version = "1.10.0" }
lalrpop-util       = { version = "0.20.0" }
logos              = { version = "0.14.0" }
pretty             = { version = "0.12.3" }
text-size          = { version = "1.1.1" }
ustr               = { version = "1.0.0" }

[build-dependencies]
lalrpop = { version = "0.20.0" }

[dev-dependencies]
expect-test = { version = "1.4.1" }

[profile.dev]
opt-level = 0

debug            = 0
debug-assertions = true
overflow-checks  = true
panic            = "abort"
strip            = "debuginfo"

codegen-units = 256
incremental   = true

lto = false

[profile.release]
opt-level = 3

debug            = 0
debug-assertions = false
overflow-checks  = false
panic            = "abort"
strip            = "debuginfo"

codegen-units = 16
incremental   = false

lto = "thin"
