[package]
name = "pion-lexer"

edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
text-size = { workspace = true }

logos = { version = "0.14.0" }

[dev-dependencies]
expect-test = { version = "1.5.0" }
