[package]
name = "pion-surface"

edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
pion-symbol = { path = "../pion-symbol" }

text-size = { workspace = true }
