[package]
name = "dependent-lambda"

edition = { workspace = true }
version = { workspace = true }

[dependencies]
common = { path = "../common" }

bumpalo = { workspace = true }
ecow    = { workspace = true }
pretty  = { version = "0.12.3" }
